
ziped = input("解凍もどきをするファイル : ")
unzip = input("解凍後のファイル名 : ")
with open(ziped,'r') as reader:
    content = reader.read()

content = content.replace('1', 'a')
content = content.replace('2', 'b')
content = content.replace('3', 'c')
content = content.replace('4', 'd')
content = content.replace('5', 'e')
content = content.replace('6', 'f')
content = content.replace('7', 'g')
content = content.replace('8', 'h')
content = content.replace('9', 'i')
content = content.replace('0', 'j')
content = content.replace('①', 'k')
content = content.replace('②', 'l')
content = content.replace('③', 'm')
content = content.replace('④', 'n')
content = content.replace('⑤', 'o')
content = content.replace('⑥', 'p')
content = content.replace('⑦', 'q')
content = content.replace('⑧', 'r')
content = content.replace('⑨', 's')
content = content.replace('⑩', 't')
content = content.replace('⑪', 'u')
content = content.replace('⑫', 'v')
content = content.replace('⑬', 'w')
content = content.replace('⑭', 'x')
content = content.replace('⑮', 'y')
content = content.replace('⑯', 'z')

with open(unzip, 'w') as writer:
    writer.write(content)
