
ziping = input("圧縮もどきをするファイル : ")
ziped = input("圧縮後のファイル名 : ")
with open(ziping,'r') as reader:
    content = reader.read()

content = content.replace('a', '1')
content = content.replace('b', '2')
content = content.replace('c', '3')
content = content.replace('d', '4')
content = content.replace('e', '5')
content = content.replace('f', '6')
content = content.replace('g', '7')
content = content.replace('h', '8')
content = content.replace('i', '9')
content = content.replace('j', '0')
content = content.replace('k', '①')
content = content.replace('l', '②')
content = content.replace('m', '③')
content = content.replace('n', '④')
content = content.replace('o', '⑤')
content = content.replace('p', '⑥')
content = content.replace('q', '⑦')
content = content.replace('r', '⑧')
content = content.replace('s', '⑨')
content = content.replace('t', '⑩')
content = content.replace('u', '⑪')
content = content.replace('v', '⑫')
content = content.replace('w', '⑬')
content = content.replace('x', '⑭')
content = content.replace('y', '⑮')
content = content.replace('z', '⑯')

with open(ziped, 'w') as writer:
    writer.write(content)
